export default [
  {
    id: 1,
    img: "../images/Barcelona.jpg",
    rating: 5.0,
    reviewCount: 400,
    country: "Spain",
    titile: "Barcelona",
    price: 400,
  },
  {
    id: 2,
    img: "../images/Madrid.jpg",
    rating: 5.0,
    reviewCount: 1400,
    country: "Spain",
    titile: "Madrid",
    price: 300,
  },
  {
    id: 3,
    img: "../images/Alicante.jpg",
    rating: 3.0,
    reviewCount: 100,
    country: "Spain",
    titile: "Alicante",
    price: 100,
  },
  {
    id: 4,
    img: "../images/Tarragona.jpg",
    rating: 4.0,
    reviewCount: 600,
    country: "Spain",
    titile: "Tarragona",
    price: 390,
  },
  {
    id: 5,
    img: "../images/Segovia.jpg",
    rating: 3.6,
    reviewCount: 35,
    country: "Spain",
    titile: "Segovia",
    price: 150,
  },
];
